server:
  port: 8888
spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.160:8848 # Nacos 服务器地址
        namespace:  insight_shaowei
      config:
        server-addr: 192.168.10.160:8848 # Nacos 配置中心地址
        file-extension: yaml
    gateway:
     discovery:
        locator:
         enabled: true
     routes:
     - id: neo_route
       uri: http://www.ityouknow.com
       predicates:
         - Path=/spring-cloud
#     - id: add_request_parameter_route
#       uri: http://localhost:8889
#       filters:
#       - AddRequestParameter=foo, bar
#       predicates:
#         - Method=GET
     - id: lb_nacos
       uri: lb://user-service
       filters:
       - AddRequestParameter=foo, bar123
       predicates:
         - Path=/user/** # 匹配 /user/** 路径的请求
     - id: lb_nacos01
       uri: lb://user-service
       filters:
        - StripPrefix=1 # 去掉前缀 /user01
       predicates:
         - Path=/user01/** # 匹配 /user01/** 路径的请求